============================= test session starts ==============================
platform linux -- Python 3.6.9, pytest-5.3.2, py-1.6.0, pluggy-0.13.1
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/home/smburns/stevenmburns/adventofcode/2017/14/.hypothesis/examples')
rootdir: /home/smburns/stevenmburns/adventofcode/2017/14, inifile: pytest.ini
plugins: hypothesis-4.5.1, timeout-1.3.4, tap-2.3, xdist-1.31.0, forked-1.1.3, parallel-0.0.10, md-0.1.1, cov-2.6.0
collected 4 items

test_A.py sFss                                                           [100%]

=================================== FAILURES ===================================
___________________________________ test_AA ____________________________________

    def test_AA():
>       assert 1242 == main2('flqrgnkx')
E       AssertionError: assert 1242 == 1
E        +  where 1 = main2('flqrgnkx')

test_A.py:96: AssertionError
----------------------------- Captured stdout call -----------------------------
##.
.#.
...
seed (0, 0)
(0, 0) 0
	 (1, 0)
(1, 0) 0
	 (2, 0)
(2, 0) 0
	 (2, 1)
(2, 1) 0
	 (1, 1)
(1, 1) 0
	 (0, 1)
(0, 1) 0
	 (0, 2)
(0, 2) 0
	 (1, 2)
(1, 2) 0
	 (2, 2)
(2, 2) 0
========================= 1 failed, 3 skipped in 0.40s =========================
